### ISSUE TITLE
Advanced settings menu

### ISSUE THREAD

**Issue by wgurecky** [wgurecky/pyReactor#8]
## Description
Provide a way to adjust reactivity coefficients, reactor volume, cross sections, rod worth curve, ect. in an advanced menu.
Additionally, add presets for RBMK and PWR.

## Tasks

- [ ] Expose reactor parameters though a nice reactor physics interface.
- [ ] Create additional menu in GUI.  Link gui buttons/boxes with the reactor physics interface.
- [ ] Create presets to set reactor parameters to pre-defined values.
